[build-system]
requires = [
    "setuptools>=42",
    "wheel",
	"setuptools-git-versioning",
	"RPi.GPIO",
	"spidev",
	"Pillow",
	"numpy",
]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = false